# Generated by Django 4.0.5 on 2022-06-17 00:25

import apps.utils
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatanalysis",
            name="word_cloud_pic",
            field=models.ImageField(blank=True, null=True, upload_to=apps.utils.RandomFileName("wordclouds")),
        ),
        migrations.AlterField(
            model_name="chatanalysis",
            name="chat_file",
            field=models.FileField(
                storage=django.core.files.storage.FileSystemStorage(base_url="/private_files", location="usersfiles"),
                upload_to="chats",
            ),
        ),
    ]
