# Generated by Django 4.0.5 on 2022-06-17 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_chatanalysis_word_cloud_pic_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatanalysis",
            name="task_id",
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
