# Generated by Django 4.0.5 on 2022-06-17 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0003_chatanalysis_task_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatanalysis",
            name="telegram_id",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
