# Generated by Django 4.0.5 on 2022-06-17 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0004_chatanalysis_telegram_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatanalysis",
            name="telegram_id",
            field=models.CharField(blank=True, default="", max_length=40),
            preserve_default=False,
        ),
    ]
