# Generated by Django 4.0.5 on 2022-06-28 10:42

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0006_chatanalysis_error_text"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="chatanalysis",
            name="dashboard_chatanalysis_status_valid",
        ),
        migrations.AddField(
            model_name="chatanalysis",
            name="language",
            field=models.CharField(choices=[("ENG", "English"), ("RUS", "Russian")], default="RUS", max_length=3),
        ),
        migrations.AlterField(
            model_name="chatanalysis",
            name="chat_file",
            field=models.FileField(
                storage=django.core.files.storage.FileSystemStorage(location="usersfiles"), upload_to="chats"
            ),
        ),
        migrations.AddConstraint(
            model_name="chatanalysis",
            constraint=models.CheckConstraint(
                check=models.Q(("status__in", ("READY", "PROCESSING", "ERROR"))),
                name="dashboard_chatanalysis_status_valid",
            ),
        ),
    ]
