# Generated by Django 4.0.6 on 2022-07-08 10:47

from django.db import migrations, models
import django.db.models.deletion
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0009_chatanalysis_results"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShareLink",
            fields=[
                (
                    "id",
                    model_utils.fields.UrlsafeTokenField(
                        editable=False, factory=None, max_length=128, primary_key=True, serialize=False
                    ),
                ),
                (
                    "analysis",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="dashboard.chatanalysis"),
                ),
            ],
        ),
    ]
