# Generated by Django 4.0.6 on 2022-07-21 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0012_alter_chatanalysis_chat_platform"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="chatanalysis",
            constraint=models.CheckConstraint(
                check=models.Q(("chat_platform__in", ("-", "Telegram", "WhatsApp", "Facebook"))),
                name="dashboard_chatanalysis_chat_platform_valid",
            ),
        ),
    ]
