# Generated by Django 4.0.6 on 2022-07-23 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0014_alter_chatanalysis_options_alter_sharelink_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatanalysis",
            name="custom_stoplist",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
