# Generated by Django 4.0.6 on 2022-09-04 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="userprofile",
            name="authentication_userprofile_language_valid",
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="language",
            field=models.CharField(
                blank=True,
                choices=[("", " "), ("en", "English"), ("ru", "Russian"), ("uk", "Ukrainian")],
                default="",
                max_length=10,
            ),
        ),
        migrations.AddConstraint(
            model_name="userprofile",
            constraint=models.CheckConstraint(
                check=models.Q(("language__in", ["", "en", "ru", "uk"])),
                name="authentication_userprofile_language_valid",
            ),
        ),
    ]
