# Generated by Django 4.0.6 on 2022-09-07 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_remove_userprofile_authentication_userprofile_language_valid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="language",
            field=models.CharField(
                blank=True,
                choices=[("", "Current"), ("en", "English"), ("ru", "Russian"), ("uk", "Ukrainian")],
                default="",
                max_length=10,
            ),
        ),
    ]
