repos:
# Fixes the spaces
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v2.3.0
      hooks:
          - id: end-of-file-fixer
          - id: trailing-whitespace
# Black
    - repo: https://github.com/ambv/black
      rev: 22.3.0
      hooks:
      - id: black
        language_version: python3.10
# Flake8
    - repo: https://github.com/pycqa/flake8
      rev: 4.0.1
      hooks:
      - id: flake8
# Pytest
    - repo: local
      hooks:
        - id: tests
          name:  tests
          stages: [push]
          entry: pytest
          language: system
          always_run: true
          pass_filenames: false
