version: "3.9"

services:
  db:
    restart: always
    image: postgres:14.4-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  web:
    build: .
    restart: unless-stopped
    container_name: django_web
    command: bash -c "chmod +x /code/docker-entry-point.sh && /code/docker-entry-point.sh"
    volumes:
      - ./data/usersfiles:/code/usersfiles
      - ./data/media:/code/media
      - ./data/staticfiles:/code/staticfiles
      - ./data/logs:/code/logs
    ports:
      - "8080:8080"
    environment:
      - DJANGO_ENV=production
      - DJANGO_DATABASE_HOST=db
      - DJANGO_DATABASE_PORT=5432
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - CELERY_BROKER_URL=redis://:${REDIS_PASSWORD}@redis:6379/0
      - DOMAIN_NAME=${DOMAIN_NAME}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DJANGO_CACHE_URL=redis://redis:6379/1
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    depends_on:
      - db
  nginx:
    restart: always
    build: "nginx"
    ports:
      - "8000:80"
    volumes:
      - ./data/staticfiles:/www/static
      - ./data/media:/www/media
  redis:
    restart: always
    container_name: "redis"
    image: bitnami/redis:latest
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - "6379:6379"
  celery:
    restart: always
    build:
      context: .
    command: celery -A core worker -l INFO
    volumes:
      - ./data/usersfiles:/code/usersfiles
      - ./data/media:/code/media
      - ./data/staticfiles:/code/staticfiles
      - ./data/logs:/code/logs
    environment:
      - DJANGO_ENV=production
      - DJANGO_DATABASE_HOST=db
      - DJANGO_DATABASE_PORT=5432
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - CELERY_BROKER_URL=redis://:${REDIS_PASSWORD}@redis:6379/0
      - DOMAIN_NAME=${DOMAIN_NAME}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DJANGO_CACHE_URL=redis://redis:6379/1
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    depends_on:
      - db
      - redis
      - web

volumes:
    pgdata:
