version: "3.9"

services:
  db:
    restart: always
    image: postgres:14.4-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  web:
    build: .
    restart: unless-stopped
    container_name: django_web
    command: bash -c "chmod +x /code/docker-entry-point.sh && /code/docker-entry-point.sh"
    volumes:
      - ./data/usersfiles:/code/usersfiles
      - ./data/media:/code/media
      - ./data/staticfiles:/code/staticfiles
      - ./data/logs:/code/logs
    ports:
      - "8080:8080"
    environment:
      - DJANGO_ENV=production
      - DJANGO_DATABASE_HOST=db
      - DJANGO_DATABASE_PORT=5432
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq3:5672/
      - DOMAIN_NAME=${DOMAIN_NAME}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
    depends_on:
      - db
  nginx:
    restart: always
    build: "nginx"
    ports:
      - "8000:80"
    volumes:
      - ./data/staticfiles:/www/static
      - ./data/media:/www/media
  rabbitmq3:
    container_name: "rabbitmq"
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
  celery:
    restart: always
    build:
      context: .
    command: celery -A core worker -l INFO
    volumes:
      - ./data/usersfiles:/code/usersfiles
      - ./data/media:/code/media
      - ./data/staticfiles:/code/staticfiles
      - ./data/logs:/code/logs
    environment:
      - DJANGO_ENV=production
      - DJANGO_DATABASE_HOST=db
      - DJANGO_DATABASE_PORT=5432
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq3:5672/
      - DOMAIN_NAME=${DOMAIN_NAME}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
    depends_on:
      - db
      - rabbitmq3
      - web

volumes:
    pgdata:
