[tool.black]
line-length = 119
include = '\.pyi?$'
exclude = '''
/(
    \.git
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
)/
'''

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "core.settings"
django_debug_mode = true
python_files = ["test*.py"]
pythonpath = "chatalyze"
log_cli = 1

[tool.isort]
profile = "black"
