# Generated by Django 4.0.6 on 2022-07-28 22:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SiteConfiguration",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "close_for_maintenance",
                    models.BooleanField(default=False, help_text="Close this site for visitors (except home page)."),
                ),
                (
                    "max_file_size",
                    models.IntegerField(
                        default=100,
                        help_text="Maximum size for the uploaded chat file in MB.",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
            ],
            options={
                "verbose_name": "Site Configuration",
            },
        ),
    ]
