# Generated by Django 4.0.6 on 2022-07-28 23:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="siteconfiguration",
            name="close_for_maintenance",
            field=models.BooleanField(
                default=False,
                help_text="Close this site (except home page) for visitors.",
                verbose_name="Close for maintenance",
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="max_file_size",
            field=models.IntegerField(
                default=100,
                help_text="Maximum size for the uploaded chat file in MB.",
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Max. file size",
            ),
        ),
    ]
